name: "Generate and scan SBOM"
description: Generate and scan a Software Bill of Materials (SBOM) for vulnerabilities using CycloneDX and Trivy.

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

    - name: Generate SBOM
      run: ./gradlew cyclonedxBom
      shell: bash

    - name: Vulnerability scan
      uses: wetransform/gha-trivy@43c9b715bc1afe1bc3984b09aeac07233c9911e3 # v2.7.0
      with:
        scan-ref: "build/reports/cyclonedx/bom.json"
        upload-scan-ref: true
        junit-test-output: "trivy.xml"
        create-test-report: true
        report-retention-days: 30
