plugins {
  id 'hale.migrated-groovy'
}

hale {
  bundleName = 'OrientDB temporary instance store'
}

dependencies {
  implementation libs.slf4jplus.api
  implementation libs.commons.io

  implementation project(':common:plugins:eu.esdihumboldt.hale.common.core')
  implementation project(':common:plugins:eu.esdihumboldt.hale.common.align')
  implementation project(':common:plugins:eu.esdihumboldt.hale.common.instance')
  implementation project(':common:plugins:eu.esdihumboldt.hale.common.schema')
  implementation project(':common:plugins:eu.esdihumboldt.hale.common.instance.orient')
  implementation project(':common:plugins:eu.esdihumboldt.hale.common.instance.store')

  testImplementation testLibs.junit4
  testImplementation project(':common:plugins:eu.esdihumboldt.hale.common.instance.store.test')
}
